name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - developer
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - developer

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    - name: Build
      run: npm run build

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.6.0'

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_POND_06EAF6D03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "Front-end/src"  # Verify this path
          api_location: ""   # If you have an API, specify its location
          output_location: "dist"  # Verify this path
